services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql