services:
  web:
    networks: [frontend,backend]
    build:
      context: ./services/web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    depends_on:
       db:
        condition: service_healthy
    expose: ["80"]
  db:
    networks: [backend]
    image: mariadb:10.5
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$${MYSQL_ROOT_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
  phpmyadmin:
    networks: [frontend,backend]
    image: phpmyadmin:5
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      web:
        condition: service_started
volumes:
  dbdata:

networks:
  frontend:
  backend: